replicaCount: 2

image:
  repository: devacrregistry123.azurecr.io/devops-demo
  tag: staging-4fbc3026273b00f510696081c337e2cadefd329f
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: myapp.local