replicaCount: 2

image:
  repository: devops-demo
  tag: staging-84ddd372631e18ccb30ab7896f7dbdc1f54ea105
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: myapp.local