replicaCount: 1

image:
  repository: devacrregistry123.azurecr.io/devops-demo
  tag: staging-260eeb7b88be554d85340f555d3678692d5b29cb
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: myapp.local