name: Staging DevSecOps Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: devops-demo
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      TAG: staging-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🧠 SonarCloud Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 📦 Dependency Scan (OWASP)
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "devops-demo"
          path: "."
          format: "HTML"

      # 🐳 Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

      # 🔐 Trivy Scan (fail on HIGH/CRITICAL)
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          severity: 'HIGH,CRITICAL'
          exit-code: 1

      # 🔑 Login to ACR
      - name: Login to ACR
        run: |
          echo $ACR_PASSWORD | docker login $REGISTRY -u $ACR_USERNAME --password-stdin
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

      # 📤 Push Image
      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$TAG

      # 📝 Update Helm values.yaml
      - name: Update Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin gitops
          git checkout gitops

          # update image tag
          sed -i "s/tag:.*/tag: $TAG/" helm/values.yaml

          git add helm/values.yaml
          git commit -m "Update image tag to $TAG"
          git push origin gitops